---
apiVersion: iam.aws.example.cloud/v1beta1
kind: Role
metadata:
  name: example-role
  namespace: assert-role
  labels:
    controlling.example.cloud/cost-reference: "123456789"
    controlling.example.cloud/owner: example
    controlling.example.cloud/product: example
    tags.example.cloud/account: "123456789101"
    tags.example.cloud/zone: "dev"
    tags.example.cloud/environment: "dev"
    tags.example.cloud/protection-requirement: "dev"
    tags.example.cloud/repourl: "x-generate"
spec:
  deletionPolicy: Delete
  forProvider:
    assumeRolePolicyDocument: | 
      {
        "Version": "2012-10-17",
        "Statement": [
          {
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                  "Service": "ec2.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
          }
        ]
      }     
    description: "my example"
  providerConfigRef:
    name: 123456789101-example