---
apiVersion: kms.aws.example.cloud/v1alpha1
kind: Key
metadata:
  name: example-key
  namespace: assert-kms
  labels:
    external-name: example-key
    controlling.example.cloud/cost-reference: "123456789"
    controlling.example.cloud/owner: example
    controlling.example.cloud/product: example
    tags.example.cloud/account: "123456789101"
    tags.example.cloud/zone: "dev"
    tags.example.cloud/environment: "dev"
    tags.example.cloud/protection-requirement: "dev"
    tags.example.cloud/repourl: "x-generate"
  annotations:
    uptest.upbound.io/conditions: "Ready=False"
    uptest.upbound.io/post-assert-hook: "../../test/tests/package/kms-key/post-assert.sh ${KUBECTL} ${KUTTL}"
spec:
  forProvider:
    region: eu-central-1
    policy: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::123456789012:root"
            },
            "Action": "kms:*",
            "Resource": "*"
          }
        ]
      }
  providerConfigRef:
    name: 123456789101-example